### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by walid-omari** [zohir19/pxe_boot#1]
- [ ] - SSH keys for root user across the cluster + enable root in ubuntu
- [x] - serve hostname from DHCP
- [x] - fixed IP in DHCP
- [ ] #4
- [x] - setup apt mirrors on chroot image
- [ ] #3
- [ ] Slurm
- [ ] LDAP integration with AD and KeyCloak
- [ ] Drivers IB+CUDA ...
- [ ] IPMI + Redfish
- [ ] Package Management (Modules + spack)
- [ ] Containers +Slurm
- [ ] Storage
- [ ] Image from Node
- [ ] mount /run /var /tmp as tmpfs using systemd mounts on diskless boot
- [ ] format node (run install script) based on format choice (from cluster DB or file) 
- [ ] #2
